# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-23 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('btf_saldo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento2',
            name='dtinclusao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='inclusao registro'),
        ),
        migrations.AddField(
            model_name='lancamento2',
            name='dttroca',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='quando foi a troca'),
        ),
    ]
