# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-26 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btf_saldo', '0003_auto_20180426_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Regiao')),
            ],
        ),
        migrations.AddField(
            model_name='talento',
            name='regiao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='btf_saldo.Regiao', verbose_name='Regiao'),
            preserve_default=False,
        ),
    ]
