# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-21 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('btf_saldo', '0012_auto_20180509_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Qual foi a troca')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Créditos de Tempo')),
                ('dttroca', models.DateField(default=django.utils.timezone.now, verbose_name='quando foi a troca')),
                ('dtinclusao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='inclusao registro')),
                ('dtprocesso', models.DateTimeField(verbose_name='processo')),
                ('status', models.CharField(help_text='Status do Lacamento', max_length=2, verbose_name='Status')),
                ('credito_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btf_saldo.CadastroAUX', verbose_name='quem recebe os créditos')),
                ('debito_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btf_saldo.Cadastro', verbose_name='quem transfere os creditos')),
            ],
        ),
        migrations.RemoveField(
            model_name='lancamento2',
            name='credito_fk',
        ),
        migrations.RemoveField(
            model_name='lancamento2',
            name='debito_fk',
        ),
        migrations.RemoveField(
            model_name='table_temp',
            name='nome1',
        ),
        migrations.RemoveField(
            model_name='table_temp',
            name='nome2',
        ),
        migrations.AlterField(
            model_name='talento',
            name='quem',
            field=models.ForeignKey(help_text='Digite seu nome igual a planilha de Créditos', on_delete=django.db.models.deletion.CASCADE, to='btf_saldo.Cadastro', verbose_name='quem é você'),
        ),
        migrations.DeleteModel(
            name='Lancamento2',
        ),
        migrations.DeleteModel(
            name='Table_Temp',
        ),
    ]
