# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-16 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btf_saldo', '0013_auto_20180621_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='qual o seu nome?')),
                ('nomefb', models.CharField(max_length=50, verbose_name='qual o nome que você usa no facebook?')),
                ('paginafb', models.CharField(max_length=150, verbose_name='cole aqui a URL ou link do seu perfil no facebook')),
                ('localizacao', models.CharField(max_length=100, verbose_name='onde você mora')),
                ('celular', models.CharField(max_length=11, verbose_name='seu telefone')),
                ('celuar_visivel', models.BooleanField(verbose_name='Permite divulgar o seu telefone para outros associados?')),
                ('email', models.CharField(max_length=50, verbose_name='informe seu email')),
                ('senha', models.CharField(max_length=10, verbose_name='informe uma senha')),
                ('nm_referencia1', models.CharField(max_length=50, verbose_name='Referência Pessoal 1')),
                ('tel_referencia1', models.CharField(max_length=11, verbose_name='Telefone Referência 1')),
                ('fb_referencia1', models.CharField(max_length=150, verbose_name='Perfil Facebook Referencia1')),
                ('nm_referencia2', models.CharField(max_length=50, verbose_name='Referência Pessoal 2')),
                ('tel_referencia2', models.CharField(max_length=11, verbose_name='Telefone Referência 2')),
                ('fb_referencia2', models.CharField(max_length=150, verbose_name='Perfil Facebook Referencia2')),
                ('nm_referencia3', models.CharField(max_length=50, verbose_name='Referência Pessoal 3')),
                ('tel_referencia3', models.CharField(max_length=11, verbose_name='Telefone Referência 3')),
                ('fb_referencia3', models.CharField(max_length=150, verbose_name='Perfil Facebook Referencia3')),
                ('comosoube', models.TextField(max_length=300, verbose_name='como soube do Banco de Tempo')),
                ('sabecomoparticipar', models.TextField(max_length=500, verbose_name='já sabe como participar do grupo')),
                ('cadastro_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btf_saldo.Cadastro', verbose_name='Quem é vc no nosso cadastro')),
            ],
        ),
    ]
