# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-16 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btf_saldo', '0014_precadastro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precadastro',
            old_name='celuar_visivel',
            new_name='celular_visivel',
        ),
    ]
