# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-24 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('btf_saldo', '0015_auto_20180716_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='dt_bloqueio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='dt_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='dt_liberado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='liberado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precadastro',
            name='emailconfirmado',
            field=models.BooleanField(default=True, verbose_name='email confirmado'),
            preserve_default=False,
        ),
    ]
